AndbosonFilmzBundle_films_list:
    resource: "@AndbosonFilmzBundle/Resources/config/routing/film.yml"
    prefix:   /

AndbosonFilmzBundle_cat:
      resource: "@AndbosonFilmzBundle/Resources/config/routing/category.yml"
      prefix:   /cat

AndbosonFilmzBundle_genre:
        resource: "@AndbosonFilmzBundle/Resources/config/routing/genre.yml"
        prefix:   /genre

AndbosonFilmzBundle_comment:
        resource: "@AndbosonFilmzBundle/Resources/config/routing/comments.yml"
        prefix:   /comment

#
#_login:
#    pattern:  /login
#    defaults: { _controller: "AndbosonFilmzBundle:Secured:login" }
#
#_security_check:
#    pattern:   (new|edit)
#    defaults: { _controller: "AndbosonFilmzBundle:Secured:securityCheck" }
#
#logout:
#    path: /logout
#    defaults: { _controller: "AndbosonFilmzBundle:Secured:logout" }

