parameters:
#    andboson_filmz.example.class: Andboson\FilmzBundle\Example

services:
#    andboson_filmz.example:
#        class: %andboson_filmz.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
